### ISSUE TITLE
Question about linux support

### ISSUE THREAD

**Issue by vortulon** [GRX005/McOverTor#1]
---

Hi! I recently discovered your project and I'm really excited to learn if Linux support is coming soon! A large player base is eager to try out this mod, and I can't wait to see how it grows!

---

**Comment by GRX005** [comment]
Sure, I'll look into it in the next update.

**Comment by vortulon** [comment]
Happy to hear that! Goodluck

**Comment by vortulon** [comment]
@GRX005  Hey good news pal! It works on arch linux! I just had to install the tor package, tor browser and nyx

**❯ sudo pacman -S tor torbrowser-launcher nyx** 

is the command for anyone wondering, 
have fun and continue to develop this mod bro! good luck, just add on the page that you need to use that command and install those packages for it to work, it might work only if you installed the tor package, i got everything just to make sure

**Comment by vortulon** [comment]
edit after some trying to get the mod working: its really buggy, im gonna try to find a fix tho

**Comment by vortulon** [comment]
https://mclo.gs/ZpniunG

heres the log
running 1.21.1 quilt on prism launcher flatpak on arch linux

**Comment by vortulon** [comment]
https://mclo.gs/ZpniunG

heres the log
running 1.21.1 quilt on prism launcher flatpak on arch linux

**Comment by BlvDeLxRd** [comment]
crash log after install torbrowser-launcher packet. i use fedora 40. https://mclo.gs/UXsa2N0

**Comment by vortulon** [comment]
hi! the developer recently released a beta for linux
its working perfectly on my arch install but you should all test it on ur distros

https://github.com/GRX005/McOverTor/releases/tag/Linux
