### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Zitrone30** [GRX005/McOverTor#2]
Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
When using the new Linux support version:

- Crashes when you click on cancel [Logs](https://mclo.gs/bYOB3bd)

- Some kind of issue in the `geoio6` file as seen in these [Logs](https://mclo.gs/MV6NprL)

- Does not give you any in game notification when it can´t bind the Port because external tor is already running [Logs](https://mclo.gs/FtZm0j2)

Screenshot shows how it looks with the geoip6 or tor already running problem
![Screenshot from 2024-11-14 18-24-27](https://github.com/user-attachments/assets/054c8cb7-c7f0-489e-870a-056b4972b71e)

**Comment by GRX005** [comment]
Yeah it tries to kill Tor using the killall cmd, but it seems it doesn't exist on your distro? Is there a command like taskkill on windows that exists on all linux distros? If not I guess I can just add a screen that tells the person to close Tor. As for the geoIP6 file, it's Tor's error so maybe it didn't extract the file properly there, or idk about that one.

**Comment by Zitrone30** [comment]
> Yeah it tries to kill Tor using the killall cmd, but it seems it doesn't exist on your distro? Is there a command like taskkill on windows that exists on all linux distros? If not I guess I can just add a screen that tells the person to close Tor. As for the geoIP6 file, it's Tor's error so maybe it didn't extract the file properly there, or idk about that one.

I have killall maby it is just missing permission and needs sudo or smth idk. for the tor thing, are there any dependencies i have to install outside of mine craft?

**Comment by GRX005** [comment]
Well that's weird since it says  "Cannot run program "killall": error=2, No such file or directory", so I guess it couldn't find tor which is weird since it's already running in some way, or maybe yeah it's just misses perms, I guess tomorrow I'll add a screen where it says it failed to close Tor and not crash the game.
No, you shouldn't need to install any deps.
